/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.dialog {
	import laya.ui.*;
	import laya.display.*;

	public class EMailUI extends Dialog {

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"Dialog","props":{"width":920,"height":438},"compId":2,"child":[{"type":"Image","props":{"y":219,"x":460,"skin":"setting/dialog.png","anchorY":0.5,"anchorX":0.5},"compId":3},{"type":"Button","props":{"y":45,"x":870,"stateNum":2,"skin":"setting/btn_close.png","name":"close","anchorY":0.5,"anchorX":0.5},"compId":5}],"loadList":["setting/dialog.png","setting/btn_close.png"],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}