/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.dialog {
	import laya.ui.*;
	import laya.display.*;

	public class SettingUI extends Dialog {

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"Dialog","props":{"width":920,"height":438},"compId":2,"child":[{"type":"Image","props":{"y":219,"x":460,"skin":"setting/dialog.png","anchorY":0.5,"anchorX":0.5},"compId":3,"child":[{"type":"Image","props":{"y":45,"x":460,"skin":"setting/name.png","anchorY":0.5,"anchorX":0.5},"compId":4}]},{"type":"Sprite","props":{"y":0,"x":10,"width":900,"name":"content"},"compId":5,"child":[{"type":"Button","props":{"y":45,"x":860,"stateNum":2,"skin":"setting/btn_close.png","name":"close","anchorY":0.5,"anchorX":0.5},"compId":6}]}],"loadList":["setting/dialog.png","setting/name.png","setting/btn_close.png"],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}